#!/usr/bin/env python3
"""Fail if the hand-authored API pages disagree with the installed ``combra``.

The API reference under ``docs/api/`` is written as explicit ``py:function`` /
``py:class`` / ``py:method`` directives rather than generated by autodoc, so
nothing stops a signature here from drifting away from the code. This script is
that guard: it imports ``combra``, walks every directive, and reports

* documented objects that no longer exist;
* public names in a module's ``__all__`` that no page documents;
* documented signatures whose parameter list differs from the real one.

Run it from the repo root (``python docs/check_api_drift.py``); exits non-zero
on any finding so CI can gate on it.
"""

from __future__ import annotations

import importlib
import inspect
import json
import os
import pathlib
import re
import sys

DOCS_ROOT = pathlib.Path(__file__).parent
DOCS_API = DOCS_ROOT / "api"

DIRECTIVE = re.compile(r"^`{3,}\{py:(function|class|method|attribute|data|exception)\}\s+(.+)$")

# Modules whose public surface the API pages are expected to cover.
SUBMODULES = [
    "angles",
    "contours",
    "data",
    "ellipse",
    "fitting",
    "graph",
    "image",
    "io",
    "metrics",
    "stats",
    "utils",
    "validation",
    "viz",
]

# Names that need an optional extra to even import; skip rather than fail.
OPTIONAL_DEPS = {"torch", "pytorch_fid", "open_clip", "torchvision"}


def _split_params(sig: str) -> list[str]:
    """Parameter names from a documented signature's parenthesised part."""
    if "(" not in sig:
        return []
    inner = sig[sig.index("(") + 1 : sig.rindex(")")]
    params, depth, cur = [], 0, ""
    for ch in inner:
        if ch in "[({":
            depth += 1
        if ch in "])}":
            depth -= 1
        if ch == "," and depth == 0:
            params.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        params.append(cur)
    out = []
    for raw in params:
        name = raw.split("=")[0].split(":")[0].strip().lstrip("*")
        if name and name not in {"/", ""}:
            out.append(name)
    return out


PARAM_FIELD = re.compile(r"^:param\s+([^:]+):")


def _documented() -> dict[str, tuple[str, list[str], str, list[str]]]:
    """``fullname -> (kind, signature_params, 'file:line', param_fields)``.

    ``param_fields`` is the ``:param x:`` list written beneath the directive. It is
    checked separately from the signature because the two rot independently: the
    0.6 rename release updated every signature line and left the prose beneath it
    describing ``save_name`` / ``N`` / ``M`` / ``save``, none of which still exist.
    """
    found = {}
    for md in sorted(DOCS_API.glob("*.md")):
        lines = md.read_text().splitlines()
        for lineno, line in enumerate(lines, 1):
            m = DIRECTIVE.match(line)
            if not m:
                continue
            kind, sig = m.groups()
            sig = sig.split("->")[0].strip()
            name = sig.split("(")[0].strip()
            fields: list[str] = []
            for follow in lines[lineno:]:
                if DIRECTIVE.match(follow):
                    break
                pm = PARAM_FIELD.match(follow)
                if pm:
                    fields += [x.strip() for x in pm.group(1).split(",")]
            found[name] = (kind, _split_params(sig), f"{md.name}:{lineno}", fields)
    return found


def _real_params(obj) -> list[str] | None:
    target = obj
    if inspect.isclass(obj):
        # NamedTuple results document their fields, not __init__(*args, **kwargs)
        fields = getattr(obj, "_fields", None)
        if fields is not None:
            return list(fields)
        target = obj.__init__
    try:
        params = list(inspect.signature(target).parameters)
    except (TypeError, ValueError):
        return None
    return [p for p in params if p not in {"self", "cls"}]


def _version_drift(real: str) -> list[str]:
    """Every place the docs hard-code a combra version must match the real one.

    ``index.md``'s opening example prints ``combra.__version__``, ``conf.py`` sets
    ``release`` / ``version``, and ``_static/switcher.json`` names the published
    version. All four have gone stale at least once each
    (the index block claimed 0.6.0 against an installed 0.7.1), because nothing
    reads them back. This does.
    """
    problems = []
    short = ".".join(real.split(".")[:2])

    conf = (DOCS_ROOT / "conf.py").read_text()
    for key, expected in (("release", real), ("version", short)):
        m = re.search(rf'^{key} = "([^"]*)"', conf, re.M)
        if m is None:
            problems.append(f"[version] conf.py: no `{key} = \"...\"` line to check")
        elif m.group(1) != expected:
            problems.append(f"[version] conf.py: {key} = {m.group(1)!r}, combra is {expected!r}")

    switcher = json.loads((DOCS_ROOT / "_static" / "switcher.json").read_text())
    for entry in switcher:
        if entry.get("preferred") and entry.get("version") != real:
            problems.append(
                f"[version] _static/switcher.json: preferred entry is "
                f"{entry.get('version')!r}, combra is {real!r}"
            )

    index = (DOCS_ROOT / "index.md").read_text()
    m = re.search(r"^>>> combra\.__version__\n'([^']*)'", index, re.M)
    if m is None:
        problems.append("[version] index.md: no `>>> combra.__version__` example to check")
    elif m.group(1) != real:
        problems.append(f"[version] index.md: claims {m.group(1)!r}, combra is {real!r}")

    return problems


def main() -> int:
    # The docs repo cannot always import combra: it lives in a separate, private
    # repo, so a fork's PR has no access to it. Skip loudly rather than fail the
    # docs build, unless COMBRA_DRIFT_STRICT is set -- which CI does whenever the
    # COMBRA_TOKEN secret is present.
    try:
        combra = importlib.import_module("combra")
    except ImportError as exc:
        strict = os.environ.get("COMBRA_DRIFT_STRICT", "").strip() not in {"", "0", "false"}
        print(f"combra is not importable ({exc}).")
        if strict:
            print("COMBRA_DRIFT_STRICT is set -> treating this as a failure.")
            return 1
        print("SKIPPING the API-drift check. Set COMBRA_DRIFT_STRICT=1 to make this fatal.")
        return 0

    problems: list[str] = []
    doc = _documented()

    # 1. every documented object exists, with a matching parameter list
    for fullname, (kind, doc_params, where, param_fields) in sorted(doc.items()):
        if kind in {"attribute", "data"} or not fullname.startswith("combra."):
            continue
        module_path, _, leaf = fullname.rpartition(".")
        try:
            obj = getattr(importlib.import_module(module_path), leaf)
        except ModuleNotFoundError as exc:
            if (exc.name or "").split(".")[0] in OPTIONAL_DEPS:
                continue
            problems.append(f"[missing] {fullname} ({where}): {exc}")
            continue
        except (ImportError, AttributeError) as exc:
            problems.append(f"[missing] {fullname} ({where}): {exc}")
            continue

        real = _real_params(obj)
        if real is None or kind == "exception":
            continue
        if doc_params != real:
            problems.append(
                f"[signature] {fullname} ({where})\n"
                f"             docs: {doc_params}\n"
                f"             code: {real}"
            )
        # The :param: list rots independently of the signature line above it.
        ghosts = [p for p in param_fields if p not in real]
        if ghosts:
            problems.append(f"[param] {fullname} ({where}): documents non-existent {ghosts}")
        undocumented = [p for p in real if p not in param_fields] if param_fields else []
        if undocumented:
            problems.append(f"[param] {fullname} ({where}): no :param: for {undocumented}")

    # 2. every public name is documented somewhere
    documented_leaves = {n.split(".")[-1] for n in doc}
    for sub in SUBMODULES:
        try:
            mod = importlib.import_module(f"combra.{sub}")
        except ImportError as exc:  # pragma: no cover - import guard
            problems.append(f"[import] combra.{sub}: {exc}")
            continue
        for name in getattr(mod, "__all__", []):
            if name not in documented_leaves:
                problems.append(f"[undocumented] combra.{sub}.{name}")

    # 3. the version the docs claim is the version they document
    problems += _version_drift(combra.__version__)

    if problems:
        print(f"API drift: {len(problems)} problem(s)\n")
        for p in problems:
            print("  " + p)
        return 1
    print(f"API reference matches combra: {len(doc)} documented objects, no drift.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
