#!/usr/bin/env python3
"""Fail if a public ``combra`` name appears on no API page.

The reference is generated by ``autodoc``, so a documented signature can no
longer drift away from the code -- that class of error is gone. One gap remains:
nothing forces a *newly added* public name to be listed, and an object no
``autosummary`` table names simply never gets a page. This script is that guard.

For each module it compares ``__all__`` against the names listed in
``docs/api/<module>.md`` -- in ``autosummary`` tables and in ``autodata`` /
``autoclass`` / ``autofunction`` directives -- and reports

* public names in ``__all__`` that no page lists;
* names listed on a page that the module no longer exports.

Run it from the repo root (``python docs/check_api_coverage.py``); exits non-zero
on any finding so CI can gate on it.
"""

from __future__ import annotations

import importlib
import os
import pathlib
import re
import sys

DOCS_API = pathlib.Path(__file__).parent / "api"

# Modules whose public surface the API pages are expected to cover.
SUBMODULES = [
    "angles",
    "contours",
    "data",
    "ellipse",
    "fitting",
    "graph",
    "image",
    "io",
    "metrics",
    "stats",
    "utils",
    "validation",
    "viz",
]

# Names inside an ``autosummary`` block: indented, dotted-or-plain identifiers.
_AUTOSUMMARY = re.compile(r"^\.\.\s+autosummary::\s*$")
_DIRECTIVE_OPTION = re.compile(r"^\s*:\w[\w-]*:")
_AUTO_SINGLE = re.compile(r"^\s*\.\.\s+auto(?:data|class|function|method|exception)::\s+([\w.]+)")
_NAME = re.compile(r"^\s+([A-Za-z_][\w.]*)\s*$")
_CURRENTMODULE = re.compile(r"^\s*\.\.\s+(?:currentmodule|module)::\s+([\w.]+)")


def names_on_page(path: pathlib.Path, default_module: str) -> set[tuple[str, str]]:
    """Collect ``(module, name)`` for every object an API page documents.

    A page may switch ``currentmodule`` mid-file -- constants and the sharded
    ``distributed`` helpers have to be documented under the submodule that
    actually defines them, because ``lazy_loader`` leaves them without a usable
    ``__module__`` on the package. Names are therefore attributed to whichever
    module is current where they are listed, not to the page's subject.
    """
    found: set[tuple[str, str]] = set()
    current = default_module
    in_table = False
    for line in path.read_text(encoding="utf-8").splitlines():
        switch = _CURRENTMODULE.match(line)
        if switch:
            current = switch.group(1)
            in_table = False
            continue
        single = _AUTO_SINGLE.match(line)
        if single:
            found.add((current, single.group(1).split(".")[-1]))
            in_table = False
            continue
        if _AUTOSUMMARY.match(line.strip()) and line.lstrip().startswith(".."):
            in_table = True
            continue
        if not in_table:
            continue
        if not line.strip() or _DIRECTIVE_OPTION.match(line):
            continue
        entry = _NAME.match(line)
        if entry:
            found.add((current, entry.group(1).split(".")[-1]))
        else:
            in_table = False
    return found


def main() -> int:
    try:
        importlib.import_module("combra")
    except ImportError as exc:
        print(f"cannot import combra: {exc}", file=sys.stderr)
        print("The API reference is generated from it; install it first.", file=sys.stderr)
        return 1

    problems = 0
    for sub in SUBMODULES:
        page = DOCS_API / f"{sub}.md"
        if not page.exists():
            print(f"{sub}: no page at {page.relative_to(DOCS_API.parent.parent)}")
            problems += 1
            continue

        module = importlib.import_module(f"combra.{sub}")
        exported = set(getattr(module, "__all__", ()) or ())
        listed = names_on_page(page, f"combra.{sub}")

        for name in sorted(exported - {n for _, n in listed}):
            print(f"{sub}.{name}: exported but on no page")
            problems += 1

        # A name listed under a switched ``currentmodule`` is correct as long as
        # the module it is attributed to really provides it.
        for mod_name, name in sorted(listed):
            if mod_name == f"combra.{sub}":
                if name not in exported:
                    print(f"{sub}.{name}: listed on {page.name} but not exported")
                    problems += 1
                continue
            try:
                owner = importlib.import_module(mod_name)
            except ImportError:
                print(f"{mod_name}.{name}: listed on {page.name}, module not importable")
                problems += 1
                continue
            if not hasattr(owner, name):
                print(f"{mod_name}.{name}: listed on {page.name} but not defined there")
                problems += 1

    if problems:
        print(f"\n{problems} coverage problem(s).", file=sys.stderr)
        return 1
    print(f"API coverage OK across {len(SUBMODULES)} modules.")
    return 0


if __name__ == "__main__":
    if os.environ.get("COMBRA_COVERAGE_STRICT", "1") == "0":
        print("COMBRA_COVERAGE_STRICT=0 -- skipping.")
        raise SystemExit(0)
    raise SystemExit(main())
