#!/usr/bin/env python3
"""Fail if the hand-authored API pages disagree with the installed ``combra``.

The API reference under ``docs/api/`` is written as explicit ``py:function`` /
``py:class`` / ``py:method`` directives rather than generated by autodoc, so
nothing stops a signature here from drifting away from the code. This script is
that guard: it imports ``combra``, walks every directive, and reports

* documented objects that no longer exist;
* public names in a module's ``__all__`` that no page documents;
* documented signatures whose parameter list differs from the real one.

Run it from the repo root (``python docs/check_api_drift.py``); exits non-zero
on any finding so CI can gate on it.
"""

from __future__ import annotations

import importlib
import inspect
import os
import pathlib
import re
import sys

DOCS_API = pathlib.Path(__file__).parent / "api"

DIRECTIVE = re.compile(r"^`{3,}\{py:(function|class|method|attribute|data|exception)\}\s+(.+)$")

# Modules whose public surface the API pages are expected to cover.
SUBMODULES = [
    "angles",
    "contours",
    "data",
    "ellipse",
    "fitting",
    "graph",
    "image",
    "io",
    "metrics",
    "stats",
    "utils",
    "validation",
    "viz",
]

# Names that need an optional extra to even import; skip rather than fail.
OPTIONAL_DEPS = {"torch", "pytorch_fid", "open_clip", "torchvision"}


def _split_params(sig: str) -> list[str]:
    """Parameter names from a documented signature's parenthesised part."""
    if "(" not in sig:
        return []
    inner = sig[sig.index("(") + 1 : sig.rindex(")")]
    params, depth, cur = [], 0, ""
    for ch in inner:
        if ch in "[({":
            depth += 1
        if ch in "])}":
            depth -= 1
        if ch == "," and depth == 0:
            params.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        params.append(cur)
    out = []
    for raw in params:
        name = raw.split("=")[0].split(":")[0].strip().lstrip("*")
        if name and name not in {"/", ""}:
            out.append(name)
    return out


def _documented() -> dict[str, tuple[str, list[str], str]]:
    """``fullname -> (kind, documented_params, 'file:line')`` for every directive."""
    found = {}
    for md in sorted(DOCS_API.glob("*.md")):
        for lineno, line in enumerate(md.read_text().splitlines(), 1):
            m = DIRECTIVE.match(line)
            if not m:
                continue
            kind, sig = m.groups()
            sig = sig.split("->")[0].strip()
            name = sig.split("(")[0].strip()
            found[name] = (kind, _split_params(sig), f"{md.name}:{lineno}")
    return found


def _real_params(obj) -> list[str] | None:
    target = obj
    if inspect.isclass(obj):
        # NamedTuple results document their fields, not __init__(*args, **kwargs)
        fields = getattr(obj, "_fields", None)
        if fields is not None:
            return list(fields)
        target = obj.__init__
    try:
        params = list(inspect.signature(target).parameters)
    except (TypeError, ValueError):
        return None
    return [p for p in params if p not in {"self", "cls"}]


def main() -> int:
    # The docs repo cannot always import combra (it is a separate, private
    # repo — see the docs-CI note in API_DOCS_UPGRADE_PLAN.md). Skip loudly
    # rather than fail the docs build, unless COMBRA_DRIFT_STRICT is set, which
    # CI should turn on once it can install combra.
    try:
        importlib.import_module("combra")
    except ImportError as exc:
        strict = os.environ.get("COMBRA_DRIFT_STRICT", "").strip() not in {"", "0", "false"}
        print(f"combra is not importable ({exc}).")
        if strict:
            print("COMBRA_DRIFT_STRICT is set -> treating this as a failure.")
            return 1
        print("SKIPPING the API-drift check. Set COMBRA_DRIFT_STRICT=1 to make this fatal.")
        return 0

    problems: list[str] = []
    doc = _documented()

    # 1. every documented object exists, with a matching parameter list
    for fullname, (kind, doc_params, where) in sorted(doc.items()):
        if kind in {"attribute", "data"} or not fullname.startswith("combra."):
            continue
        module_path, _, leaf = fullname.rpartition(".")
        try:
            obj = getattr(importlib.import_module(module_path), leaf)
        except ModuleNotFoundError as exc:
            if (exc.name or "").split(".")[0] in OPTIONAL_DEPS:
                continue
            problems.append(f"[missing] {fullname} ({where}): {exc}")
            continue
        except (ImportError, AttributeError) as exc:
            problems.append(f"[missing] {fullname} ({where}): {exc}")
            continue

        real = _real_params(obj)
        if real is None or kind == "exception":
            continue
        if doc_params != real:
            problems.append(
                f"[signature] {fullname} ({where})\n"
                f"             docs: {doc_params}\n"
                f"             code: {real}"
            )

    # 2. every public name is documented somewhere
    documented_leaves = {n.split(".")[-1] for n in doc}
    for sub in SUBMODULES:
        try:
            mod = importlib.import_module(f"combra.{sub}")
        except ImportError as exc:  # pragma: no cover - import guard
            problems.append(f"[import] combra.{sub}: {exc}")
            continue
        for name in getattr(mod, "__all__", []):
            if name not in documented_leaves:
                problems.append(f"[undocumented] combra.{sub}.{name}")

    if problems:
        print(f"API drift: {len(problems)} problem(s)\n")
        for p in problems:
            print("  " + p)
        return 1
    print(f"API reference matches combra: {len(doc)} documented objects, no drift.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
