"""combra names that are exported but deliberately have no page.

The API reference lists only the high-level entry points (docs/api/*.md).
Everything else combra exports -- pipeline stages, helpers, result containers,
constants -- is named here instead. ``check_api_coverage.py`` requires every
exported name to be on exactly one of the two, so a new export must be triaged;
``conf.py`` renders a cross-reference to any of these as plain code rather than
failing the nitpicky build.

Modules whose whole public surface is undocumented are listed too, so that a
``:mod:`` reference to them renders as code as well.
"""

UNDOCUMENTED_MODULES = frozenset({
    "combra.contours",
    "combra.fitting",
    "combra.stats",
    "combra.utils",
    "combra.validation",
    "combra.viz",
})

UNDOCUMENTED = frozenset({
    # combra.angles
    "combra.angles.AngleDensityDisplay",
    "combra.angles.AngleSummary",
    "combra.angles.build_overlay_grid",
    "combra.angles.extract_polygons",
    "combra.angles.output_directory",
    "combra.angles.plot_density_grid",
    "combra.angles.pool_mask",
    "combra.angles.pool_regions",
    "combra.angles.Region",
    "combra.angles.resolve_overlay_rows",
    # combra.contours
    "combra.contours.contour_to_binary_mask",
    "combra.contours.draw_contours",
    "combra.contours.find_contours",
    # combra.data
    "combra.data.load_crack_annotations",
    "combra.data.load_crack_contours",
    "combra.data.microstructure_data_dir",
    "combra.data.plot_polyamide_contour",
    "combra.data.plot_polyamide_fractal",
    "combra.data.PolyamideFractureDataset",
    # combra.ellipse
    "combra.ellipse.BeamComparison",
    "combra.ellipse.MveeResult",
    "combra.ellipse.plot_beam_heatmap",
    "combra.ellipse.plot_beam_orientations",
    "combra.ellipse.plot_enclosing_ellipse",
    # combra.exceptions
    "combra.exceptions.CombraWarning",
    "combra.exceptions.IncompleteShardError",
    "combra.exceptions.UnknownFormatWarning",
    # combra.experimental
    "combra.experimental.extract_polygons",
    "combra.experimental.facets",
    "combra.experimental.gradient_snap",
    "combra.experimental.pool_regions",
    # combra.fitting
    "combra.fitting.BimodalGaussianFit",
    "combra.fitting.DistributionFit",
    "combra.fitting.fit_bimodal_gaussian",
    "combra.fitting.fit_distribution",
    "combra.fitting.fit_line",
    "combra.fitting.fit_plateau",
    "combra.fitting.LineFit",
    "combra.fitting.PlateauFit",
    # combra.graph
    "combra.graph.all_simple_paths_within_radius",
    "combra.graph.classify_edge_geometric",
    "combra.graph.classify_edge_labeled",
    "combra.graph.draw_skeleton",
    "combra.graph.enumerate_simple_paths",
    "combra.graph.evaluate_path_energies",
    "combra.graph.find_edges",
    "combra.graph.plot_optimized_energies",
    "combra.graph.plot_optimized_paths",
    "combra.graph.plot_path_length_distribution",
    "combra.graph.remove_edges_of_type",
    "combra.graph.shortest_energy_paths_all_pairs",
    "combra.graph.shortest_paths_per_endpoint",
    # combra.image
    "combra.image.augment_quadrants",
    "combra.image.bresenham_line",
    "combra.image.build_quadrant_dataset",
    "combra.image.contour_fractal_dimension",
    "combra.image.count_border_pixels_in_band",
    "combra.image.count_border_pixels_on_line",
    "combra.image.ellipse",
    "combra.image.fill_polygon",
    "combra.image.is_point_in_polygon",
    "combra.image.perpendicular_vector",
    "combra.image.render_filled_contours",
    "combra.image.resize_folder",
    "combra.image.segments_intersect",
    "combra.image.tile_images",
    "combra.image.to_uint8",
    # combra.io
    "combra.io.ANGLES_SCHEMA",
    "combra.io.BEAMS_SCHEMA",
    "combra.io.build_run_meta",
    "combra.io.flatten_hparams",
    "combra.io.progress_fraction",
    "combra.io.read_tb_scalars",
    # combra.legacy
    "combra.legacy.extract_polygons",
    "combra.legacy.output_directory",
    "combra.legacy.preprocess_image",
    # combra.metrics
    "combra.metrics.all_metrics_by_sample_size",
    "combra.metrics.angle_density_metrics_from_pooled",
    "combra.metrics.angle_metrics_by_sample_size",
    "combra.metrics.cmmd_features",
    "combra.metrics.cmmd_from_features",
    "combra.metrics.compare_pairs",
    "combra.metrics.compute_angle_metrics",
    "combra.metrics.compute_cmmd",
    "combra.metrics.compute_fd_dinov2",
    "combra.metrics.compute_fid",
    "combra.metrics.compute_gauss_metrics",
    "combra.metrics.compute_wasserstein_metrics",
    "combra.metrics.DEFAULT_ANGLE_STEP",
    "combra.metrics.degenerate_fit_reason",
    "combra.metrics.fd_dinov2_features",
    "combra.metrics.fid_features",
    "combra.metrics.find_kimg_parquets",
    "combra.metrics.find_reference",
    "combra.metrics.frechet_distance",
    "combra.metrics.frechet_from_features",
    "combra.metrics.gauss_density_metrics",
    "combra.metrics.gauss_relative_errors",
    "combra.metrics.images_to_angle_density",
    "combra.metrics.images_to_pooled_angles",
    "combra.metrics.index_by_name_step",
    "combra.metrics.load_fid_by_kimg",
    "combra.metrics.parquet_has_step",
    "combra.metrics.plot_distribution_grid",
    "combra.metrics.plot_metric_distribution",
    "combra.metrics.plot_metrics_grid",
    "combra.metrics.plot_training_curve_grid",
    "combra.metrics.summarize_metric_distribution",
    "combra.metrics.wasserstein_density_metrics",
    # combra.metrics.distributed
    "combra.metrics.distributed.all_ranks_ok",
    "combra.metrics.distributed.angle_workers",
    "combra.metrics.distributed.gather_pooled_angles",
    "combra.metrics.distributed.gather_rows",
    "combra.metrics.distributed.IMAGE_METRICS",
    # combra.stats
    "combra.stats.bimodal_gaussian",
    "combra.stats.binomial",
    "combra.stats.density_histogram",
    "combra.stats.exponential",
    "combra.stats.gaussian",
    "combra.stats.poisson",
    "combra.stats.require_density",
    "combra.stats.truncated_bimodal_gaussian",
    # combra.synth
    "combra.synth.BenchmarkResult",
    "combra.synth.Canvas",
    "combra.synth.CanvasScore",
    "combra.synth.corner_angle_error",
    "combra.synth.coverage_patch",
    "combra.synth.DIAMETER_RANGE",
    "combra.synth.edge_offset",
    "combra.synth.fit_generator",
    "combra.synth.fit_renderer",
    "combra.synth.GENERATOR",
    "combra.synth.GeneratorFit",
    "combra.synth.image_statistics",
    "combra.synth.interior_angles",
    "combra.synth.iou_per_region",
    "combra.synth.MIN_GAP",
    "combra.synth.plot_canvas",
    "combra.synth.plot_pools",
    "combra.synth.pool_polygon",
    "combra.synth.rasterize",
    "combra.synth.real_reference",
    "combra.synth.reflex_share",
    "combra.synth.render",
    "combra.synth.RENDERER",
    "combra.synth.RendererFit",
    "combra.synth.score_canvas",
    "combra.synth.shoelace",
    "combra.synth.SIZE_BINS",
    "combra.synth.STAT_KEYS",
    "combra.synth.summarize",
    "combra.synth.SUPERSAMPLE",
    "combra.synth.TruthRegion",
    # combra.utils
    "combra.utils.Bunch",
    # combra.validation
    "combra.validation.check_fractal_dimension",
    # combra.viz
    "combra.viz.axis_style",
    "combra.viz.export_png",
    "combra.viz.MARKER_GLYPHS",
    "combra.viz.MARKERS",
    "combra.viz.METRIC_PALETTE",
    "combra.viz.SERIES_PALETTE",
})
